version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ulingua-postgres-dev
    environment:
      POSTGRES_DB: ulingua-dev-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab3dRfGh7J9K
    ports:
      - "5432:5432"
    volumes:
      - ulingua-postgres-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ulingua-redis-dev
    command: ["redis-server", "--requirepass", "Ab3dRfGh7J9K"]
    ports:
      - "6379:6379"
    volumes:
      - ulingua-redis-dev-data:/data

volumes:
  ulingua-postgres-dev-data:
  ulingua-redis-dev-data:
